spring:
  datasource:
    url: jdbc:mysql://localhost:3306/commerce
    username: root
    password: myseceretpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    contexts: dev, faker
    change-log: classpath:db/master.xml
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl