spring:
  datasource:
    url: jdbc:mysql://localhost:3306/commerce
    username: sa
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    contexts: dev, faker
    change-log: classpath:db/master.xml
    url: jdbc:mysql://localhost:3306/commerce
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl